#!/bin/sh
# speedwm-core
# this script is used to run stuff

BINDIR="$(dirname $(command -v speedwm-core))/"

case "$1" in
"-curl-weather") clear ; curl -s wttr.in | head -n 38 | tail -n 37 && read a ;;
esac
